# docker-compose.yml

version: '3.8'

services:
  # The PostgreSQL Database Container
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: iot_db
      POSTGRES_USER: iot_user
      POSTGRES_PASSWORD: supersecretpassword
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  # Django Application Container
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app # Syncs local code changes to the container in real-time
    ports:
      - "8000:8000"
    depends_on:
      - db # Ensures the database starts before Django
      - redis # Ensures Redis starts before Django